// Generated by CoffeeScript 1.3.3
(function() {

  this.romanNumeralGenerator = function(decimal) {
    var exceeds_range, factors, glyphs, index, max_decimal, numeral, order, remainder, result, _i, _len;
    max_decimal = 4000 - 1;
    exceeds_range = "Only numbers in the range ( 1 .. " + max_decimal + " ) are supported";
    if (!(decimal <= max_decimal && decimal > 0)) {
      throw new Error("Cannot convert (" + decimal + "): " + exceeds_range);
    }
    factors = [1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1];
    glyphs = ["M", "CM", "D", "CD", "C", "XC", "L", "XL", "X", "IX", "V", "IV", "I"];
    result = "";
    for (index = _i = 0, _len = factors.length; _i < _len; index = ++_i) {
      numeral = factors[index];
      remainder = decimal % numeral;
      order = Math.floor((decimal - remainder) / numeral);
      decimal = remainder;
      result += Array(order + 1).join(glyphs[index]);
    }
    return result;
  };

}).call(this);
